'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { ChevronDown, ChevronRight, GitBranch, Layers3, Loader2, Play, Search, Sparkles, TreePine } from 'lucide-react';
import type { KLCMemory, KLCNodeRaw, KLCTree, LessonPayload } from '@/lib/types';
import { BASE, loadKLC } from '@/lib/data';
import { trackError } from '@/lib/analytics';

type Edge=[number,number,string,string,string,number|null,string];
const nodeObj=(n:KLCNodeRaw)=>({no:n[0],kanji:n[1],meaning:n[2],onyomi:n[3],kunyomi:n[4],oneLevel:n[5],leaf:n[6],leafRad:n[7],status:n[8],verification:n[9],note:n[10]});
const splitTokens=(s:string)=>String(s||'').split(/[+,、，\s]+/).map(x=>x.trim()).filter(Boolean);
const typeLabel=(s:string)=>({KLC:'KLC Kanji',RAD:'Radical / Primitive',SUP:'Supplemental',OTR:'Other'} as Record<string,string>)[s]||s;
const relationLabel=(s:string)=>({PRIMITIVE_OR_NONKLC:'Primitive / non-KLC',EARLIER_OR_SAME_KLC:'Earlier / same KLC',LATER_KLC_MNEMONIC_REF:'Later mnemonic reference'} as Record<string,string>)[s]||s;

function StrokeOrder({kanji}:{kanji:string}){const host=useRef<HTMLDivElement>(null),raw=useRef('');const [available,setAvailable]=useState(false),[loading,setLoading]=useState(true);const draw=()=>{const el=host.current;if(!el||!raw.current)return;el.innerHTML=raw.current;const svg=el.querySelector('svg');if(svg){svg.removeAttribute('width');svg.removeAttribute('height');svg.setAttribute('viewBox',svg.getAttribute('viewBox')||'0 0 109 109')}const paths=[...el.querySelectorAll('path')];paths.forEach((p:any,i)=>{let len=300;try{len=p.getTotalLength()}catch{}p.style.strokeDasharray=String(len);p.style.strokeDashoffset=String(len);p.style.animation=`kanjiStroke .48s ${i*.34}s cubic-bezier(.4,0,.2,1) forwards`})};useEffect(()=>{let dead=false;setLoading(true);setAvailable(false);(async()=>{try{const idx:Record<string,string>=await fetch(`${BASE}/assets/strokes/index.json`).then(async r=>r.ok?((await r.json()) as Record<string,string>):({}));const fn=idx[kanji];if(!fn)return;const text=await fetch(`${BASE}/assets/strokes/${fn}`).then(r=>r.ok?r.text():'');if(!text)return;raw.current=text;if(!dead){setAvailable(true);setTimeout(draw,30)}}catch(e){trackError('resource',e)}finally{if(!dead)setLoading(false)}})();return()=>{dead=true}},[kanji]);if(loading)return <div className="stroke-empty"><Loader2 className="animate-spin"/> Loading stroke vector…</div>;if(!available)return <div className="stroke-empty"><Sparkles/> Stroke-order SVG unavailable for this character.</div>;return <div className="stroke-studio"><div ref={host} className="stroke-svg"/><button className="premium-btn premium-btn-secondary" onClick={draw}><Play size={15}/> Replay strokes</button></div>}

function RecursiveNode({no,depth,maxDepth,byNo,byParent,onOpen,seen=new Set<number>()}:{no:number;depth:number;maxDepth:number;byNo:Map<number,KLCNodeRaw>;byParent:Map<number,Edge[]>;onOpen:(n:number)=>void;seen?:Set<number>}){const raw=byNo.get(no);if(!raw)return null;const n=nodeObj(raw);const cyc=seen.has(no);const next=new Set(seen);next.add(no);const edges=(byParent.get(no)||[]).slice().sort((a,b)=>a[1]-b[1]);return <div className={`recursive-node depth-${Math.min(depth,4)}`}><button className="tree-root-card" onClick={()=>onOpen(no)}><span className="font-jp">{n.kanji}</span><div><b>KLC {n.no}</b><small>{n.meaning}</small></div></button>{!cyc&&depth<maxDepth&&edges.length>0&&<div className="tree-children">{edges.map((e,i)=>{const child=e[5];const recurse=e[4]==='KLC'&&child&&e[6]!=='LATER_KLC_MNEMONIC_REF';return <div className={`tree-child ${e[6]==='LATER_KLC_MNEMONIC_REF'?'later-ref':''}`} key={`${e[0]}-${e[1]}-${i}`}><span className="tree-rail"/><button className={`tree-leaf-card ${child?'clickable':''}`} onClick={()=>child&&onOpen(child)}><span className="font-jp">{e[2]}</span><div><b>{e[3]||'component'}</b><small>{typeLabel(e[4])} · {relationLabel(e[6])}</small></div></button>{recurse&&<RecursiveNode no={child as number} depth={depth+1} maxDepth={maxDepth} byNo={byNo} byParent={byParent} onOpen={onOpen} seen={next}/>}</div>})}</div>}</div>}

export default function KanjiExplorer({data}:{data:LessonPayload}){
 const [tree,setTree]=useState<KLCTree|null>(null),[memory,setMemory]=useState<KLCMemory>({}),[query,setQuery]=useState(''),[selected,setSelected]=useState(1),[limit,setLimit]=useState(96),[depth,setDepth]=useState(3),[browserOpen,setBrowserOpen]=useState(true);
 useEffect(()=>{let dead=false;loadKLC().then(([t,m])=>{if(dead)return;setTree(t);setMemory(m);const chars=[...new Set(data.vocabulary.flatMap(v=>(v.kanji||'').match(/[\u3400-\u9fff]/g)||[]))];const first=t.nodes.find(n=>chars.includes(n[1]))||t.nodes[0];setSelected(first?.[0]||1)}).catch(e=>trackError('resource',e));return()=>{dead=true}},[data.lesson]);
 const nodes=tree?.nodes||[];const byNo=useMemo(()=>new Map<number,KLCNodeRaw>(nodes.map(n=>[n[0],n])),[nodes]);const byChar=useMemo(()=>new Map<string,KLCNodeRaw>(nodes.map(n=>[n[1],n])),[nodes]);const byParent=useMemo(()=>{const m=new Map<number,Edge[]>();for(const e of (tree?.edges||[]) as Edge[]){if(!m.has(e[0]))m.set(e[0],[]);m.get(e[0])!.push(e)}return m},[tree]);const reverse=useMemo(()=>{const m=new Map<number,Set<number>>();for(const e of (tree?.edges||[]) as Edge[]){if(e[5]){if(!m.has(e[5]))m.set(e[5],new Set());m.get(e[5])!.add(e[0])}}return m},[tree]);
 const raw=byNo.get(selected)||nodes[0],node=raw?nodeObj(raw):null,edges=(byParent.get(selected)||[]).slice().sort((a,b)=>a[1]-b[1]);const mem=node?(memory[String(node.no)]||['','',[]]):['','',[]] as [string,string,string[]];
 const lessonChars=useMemo(()=>[...new Set(data.vocabulary.flatMap(v=>(v.kanji||'').match(/[\u3400-\u9fff]/g)||[]))],[data.vocabulary]);const lessonNodes=lessonChars.map(ch=>byChar.get(ch)).filter(Boolean) as KLCNodeRaw[];const missing=lessonChars.filter(ch=>!byChar.has(ch));
 const results=useMemo(()=>{const q=query.trim().toLowerCase();const all=q?nodes.filter(n=>[n[1],n[2],n[3],n[4],n[5],String(n[0])].some(x=>String(x||'').toLowerCase().includes(q))):nodes;return all.slice(0,limit)},[nodes,query,limit]);const builds=[...(reverse.get(selected)||[])].map(n=>byNo.get(n)).filter(Boolean).slice(0,48) as KLCNodeRaw[];
 if(!tree||!node)return <div className="kanji-loading"><Loader2 className="animate-spin"/><b>Loading KLC construction tree…</b></div>;
 const open=(n:number)=>{setSelected(n);requestAnimationFrame(()=>document.querySelector('.kanji-identity')?.scrollIntoView({behavior:'smooth',block:'start'}))};
 return <div className="space-y-5 pb-8"><section className="study-header tone-kanji"><div><div className="section-kicker">KLC Kanji Construction Tree</div><h1>{tree.stats.nodes?.toLocaleString()||'2,300'} Kanji · {tree.stats.edges?.toLocaleString()||tree.edges.length.toLocaleString()} exact component edges</h1><p className="font-bn">আপনার KLC node + edge CSV অনুযায়ী visual recognition tree। Visual construction ≠ historical etymology.</p></div><TreePine className="header-big-icon"/></section>
 <section className="klc-dataset-stats"><div><b>{tree.stats.nodes||2300}</b><span>KLC nodes</span></div><div><b>{tree.stats.edges||4034}</b><span>Component edges</span></div><div><b>{tree.stats.atomic_or_root||0}</b><span>Atomic / root</span></div><div><b>{tree.stats.klc_component_edges||0}</b><span>KLC→KLC links</span></div></section>
 <section className="lesson-kanji-strip"><div><span className="section-kicker">Lesson {String(data.lesson).padStart(2,'0')} Kanji</span><b>{lessonNodes.length}/{lessonChars.length} mapped</b></div><div className="kanji-chip-scroll">{lessonNodes.map(n=><button key={n[0]} className={n[0]===selected?'active':''} onClick={()=>open(n[0])}><span>{n[1]}</span><small>{n[2]}</small></button>)}{missing.map(ch=><button key={ch} disabled><span>{ch}</span><small>Not in KLC 2300</small></button>)}</div></section>
 <button className="kanji-browser-toggle premium-btn premium-btn-secondary" onClick={()=>setBrowserOpen(v=>!v)}>{browserOpen?<ChevronDown/>:<ChevronRight/>} Search all 2,300</button>
 <div className="kanji-layout"><AnimatePresence initial={false}>{browserOpen&&<motion.aside initial={{opacity:0,x:-8}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-8}} className="kanji-browser"><label className="search-field"><Search size={17}/><input value={query} onChange={e=>{setQuery(e.target.value);setLimit(96)}} placeholder="Kanji / KLC no / meaning / reading…"/></label><div className="kanji-result-grid">{results.map(n=><button key={n[0]} className={n[0]===selected?'active':''} onClick={()=>open(n[0])}><span>{n[1]}</span><small>#{n[0]}</small></button>)}</div>{limit<nodes.length&&<button className="premium-btn premium-btn-secondary w-full" onClick={()=>setLimit(x=>x+96)}>Load more</button>}</motion.aside>}</AnimatePresence>
 <main className="kanji-detail"><motion.article key={node.no} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="kanji-identity"><div className="kanji-glyph">{node.kanji}</div><div><span className="section-kicker">KLC #{node.no} · {node.status||'Record'}</span><h2>{node.meaning}</h2>{mem[0]&&<p className="font-bn text-lg font-bold text-sakura">{mem[0]}</p>}<div className="reading-pills"><span>音 {node.onyomi||'—'}</span><span>訓 {node.kunyomi||'—'}</span><span>{node.verification||'—'}</span></div></div></motion.article>
 <section className="premium-panel"><div className="section-kicker">Exact one-level construction</div><h2 className="section-title">{node.oneLevel||node.kanji}</h2>{edges.length?<div className="component-card-grid">{edges.map((e,i)=><button key={`${e[1]}-${i}`} onClick={()=>e[5]&&open(e[5])} className={e[6]==='LATER_KLC_MNEMONIC_REF'?'later-ref':''}><span className="position">{e[1]}</span><strong className="font-jp">{e[2]}</strong><div><b>{e[3]}</b><small>{typeLabel(e[4])}</small><em>{relationLabel(e[6])}</em></div></button>)}</div>:<div className="atomic-note">Atomic / root record — immediate component edge নেই।</div>}{mem[1]&&<div className="memory-story font-bn"><b>মনে রাখার ১-লাইন গল্প</b><p>{mem[1]}</p><small>Visual memory aid — true etymology নয়</small></div>}</section>
 <section className="premium-panel recursive-tree-panel"><div className="tree-panel-head"><div><div className="section-kicker">Recursive KLC Construction</div><h2 className="section-title">True expandable component tree</h2><p className="section-subtitle">Explicit KLC→KLC links recursively expand; RAD/primitive components leaf node হিসেবে থাকে।</p></div><label>Depth<select value={depth} onChange={e=>setDepth(Number(e.target.value))}>{[1,2,3,4].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="recursive-tree-scroll"><RecursiveNode no={selected} depth={0} maxDepth={depth} byNo={byNo} byParent={byParent} onOpen={open}/></div></section>
 <div className="klc-info-grid-v42"><section className="premium-panel"><div className="section-kicker">Leaf components</div><div className="klc-token-row-v42">{splitTokens(node.leaf).map(x=><span key={x}>{x}</span>)}</div><div className="section-kicker mt-4">Leaf RAD components</div><div className="klc-token-row-v42 rad">{splitTokens(node.leafRad).map(x=><span key={x}>{x}</span>)}</div>{node.note&&<p className="verification-note">{node.note}</p>}</section><section className="premium-panel"><div className="section-kicker">Builds into</div><h2 className="section-title">Explicit KLC child links</h2><div className="builds-grid">{builds.length?builds.map(n=><button key={n[0]} onClick={()=>open(n[0])}><span>{n[1]}</span><small>KLC {n[0]}</small><b>{n[2]}</b></button>):<p className="section-subtitle">No explicit child link found.</p>}</div></section></div>
 <section className="premium-panel"><div className="section-kicker">Stroke order</div><h2 className="section-title">Animated KanjiVG studio</h2><StrokeOrder kanji={node.kanji}/></section>
 </main></div></div>
}
