'use client';

import { useMemo, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { CheckCircle2, ClipboardCheck, RotateCcw, Trophy, XCircle } from 'lucide-react';
import type { LessonPayload, MockAttempt, VocabItem } from '@/lib/types';
import { track } from '@/lib/analytics';

type Kind='jp_bn'|'bn_jp'|'kanji_reading'|'sentence';
type Q={id:string;kind:Kind;prompt:string;correct:string;options:string[];wordId:number};
function shuffle<T>(a:T[]){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function opts(correct:string,pool:string[]){const u=Array.from(new Set(pool.filter(x=>x&&x!==correct)));return shuffle([correct,...shuffle(u).slice(0,3)])}
function build(rows:VocabItem[]):Q[]{const source=shuffle(rows);const out:Q[]=[];for(let i=0;i<100;i++){const v=source[i%source.length],kind=(i%4===2&&!v.kanji?'jp_bn':['jp_bn','bn_jp','kanji_reading','sentence'][i%4]) as Kind;let prompt='',correct='',pool:string[]=[];if(kind==='jp_bn'){prompt=v.kanji||v.japanese;correct=v.bangla_meaning;pool=rows.map(x=>x.bangla_meaning)}else if(kind==='bn_jp'){prompt=v.bangla_meaning;correct=v.japanese;pool=rows.map(x=>x.japanese)}else if(kind==='kanji_reading'){prompt=v.kanji||v.japanese;correct=v.japanese;pool=rows.map(x=>x.japanese)}else{const ex=v.example?.jp||v.example?.japanese||v.japanese;prompt=ex;correct=v.example?.bn||v.bangla_meaning;pool=rows.map(x=>x.example?.bn||x.bangla_meaning)}out.push({id:`${v.id}-${i}-${kind}`,kind,prompt,correct,options:opts(correct,pool),wordId:v.id})}return shuffle(out)}
const kindLabel:Record<Kind,string>={jp_bn:'Japanese → বাংলা',bn_jp:'বাংলা → Japanese',kanji_reading:'Kanji Reading',sentence:'Sentence Meaning'};
export default function MockTest({data,onSave}:{data:LessonPayload;onSave:(a:MockAttempt)=>void}){
 const [questions,setQuestions]=useState<Q[]>([]);const [i,setI]=useState(0);const [selected,setSelected]=useState<string|null>(null);const [correct,setCorrect]=useState(0);const [breakdown,setBreakdown]=useState<Record<string,{correct:number,total:number}>>({});const [result,setResult]=useState<MockAttempt|null>(null);const q=questions[i];
 const start=()=>{setQuestions(build(data.vocabulary));setI(0);setSelected(null);setCorrect(0);setBreakdown({});setResult(null);track('quiz_event',{quiz_action:'start',lesson_number:data.lesson,question_count:100})};
 const choose=(x:string)=>{if(selected||!q)return;setSelected(x);const ok=x===q.correct;if(ok)setCorrect(c=>c+1);setBreakdown(b=>({...b,[q.kind]:{correct:(b[q.kind]?.correct||0)+(ok?1:0),total:(b[q.kind]?.total||0)+1}}))};
 const next=()=>{if(!selected)return;if(i+1>=questions.length){const c=correct+(selected===q.correct?0:0);const score=Math.round(c/100*100);const a:MockAttempt={lesson:data.lesson,score,correct:c,total:100,date:new Date().toISOString(),breakdown};setResult(a);onSave(a);setQuestions([]);track('quiz_event',{quiz_action:'complete',lesson_number:data.lesson,score_percent:score,correct_count:c,wrong_count:100-c})}else{setI(x=>x+1);setSelected(null)}};
 if(result)return <div className="space-y-5"><section className="study-header tone-mock"><div><div className="section-kicker">Mock Test Complete</div><h1>{result.score}%</h1><p>{result.correct}/{result.total} correct</p></div><Trophy className="header-big-icon"/></section><article className="premium-panel"><div className="result-hero"><div className="score-orb">{result.score}%</div><div><h2>{result.score>=90?'Excellent work':result.score>=70?'Strong progress':'Keep reviewing'}</h2><p className="font-bn">ভুলগুলো SRS/Revision-এ আবার দেখুন এবং তারপর আরেকটি random test দিন।</p></div></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{Object.entries(result.breakdown||{}).map(([k,v])=><div className="breakdown-card" key={k}><span>{kindLabel[k as Kind]||k}</span><b>{Math.round(v.correct/Math.max(1,v.total)*100)}%</b><small>{v.correct}/{v.total}</small></div>)}</div><button className="premium-btn premium-btn-primary mt-5" onClick={start}><RotateCcw size={16}/> New 100-question test</button></article></div>;
 if(!q)return <div className="space-y-5"><section className="study-header tone-mock"><div><div className="section-kicker">JLPT N5 Mock · Lesson {String(data.lesson).padStart(2,'0')}</div><h1>100 Randomized Questions</h1><p className="font-bn">প্রতিবার নতুন order; answer করার পর correct/incorrect state পরিষ্কার দেখা যাবে।</p></div><ClipboardCheck className="header-big-icon"/></section><button onClick={start} className="mock-start"><ClipboardCheck/><div><b>Start 100-question lesson mock</b><p>{data.vocabulary.length} vocabulary items থেকে mixed question types তৈরি হবে।</p></div></button></div>;
 const pct=Math.round(i/questions.length*100);return <div className="mock-session"><div className="mock-session-top"><span>{kindLabel[q.kind]}</span><b>{i+1}/100</b></div><div className="mock-progress"><i style={{width:`${pct}%`}}/></div><AnimatePresence mode="wait"><motion.article key={q.id} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} className="mock-question"><span className="section-kicker">Choose the best answer</span><h2 className="font-jp">{q.prompt}</h2><div className="mock-options">{q.options.map(x=>{let cls='';if(selected){if(x===q.correct)cls='correct';else if(x===selected)cls='wrong'}return <button disabled={!!selected} onClick={()=>choose(x)} className={cls} key={x}><span>{cls==='correct'?<CheckCircle2/>:cls==='wrong'?<XCircle/>:null}</span><b className={q.kind==='bn_jp'||q.kind==='kanji_reading'?'font-jp':'font-bn'}>{x}</b></button>})}</div>{selected&&<button className="premium-btn premium-btn-primary mt-5" onClick={next}>{i===99?'Finish Test':'Next Question →'}</button>}</motion.article></AnimatePresence></div>
}
